- name: Setup K8S node
  hosts: test
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: insmod overlay
      community.general.modprobe:
        name: br_netfilter
        # persistent: present
        state: present
    - name: insmod br_netfilter
      community.general.modprobe:
        name: br_netfilter
        # persistent: present
        state: present
    - name: Set net.ipv4.ip_forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.d/k8s.conf
        sysctl_set: true
    - name: Set net.bridge.bridge-nf-call-iptables
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        sysctl_file: /etc/sysctl.d/k8s.conf
        value: '1'
        sysctl_set: true
    - name: Set net.bridge.bridge-nf-call-ip6tables
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        sysctl_file: /etc/sysctl.d/k8s.conf
        value: '1'
        sysctl_set: true